### ISSUE TITLE
Annotation Error related to oneOf  PropertyValues

### ISSUE THREAD

**Issue by giraygi** [TIBHannover/ols4#65]
**Describe the bug**
The error originates in annotateRelated_Class_subClassOf_Restriction_someValuesFrom_oneOf method. 

**To Reproduce**
It is seen in the rdf2json step of fibo ontology.

**Expected behavior**
The ontology should be ingested with all its data.

**Screenshots**

<details><summary>exception log</summary>
20:07:28.582 [main] INFO  u.a.e.r.a.InverseOfAnnotator - annotate inverseOf: 0
20:07:28.597 [main] INFO  u.a.e.r.a.NegativePropertyAssertionAnnotator - annotate negative property assertions: 0
20:07:28.612 [main] INFO  u.a.e.r.a.OboSynonymTypeNameAnnotator - annotate obo synonym type names: 0
20:07:28.645 [main] INFO  u.a.e.r.a.DirectParentsAnnotator - annotate direct parents: 0 
java.lang.ClassCastException: class uk.ac.ebi.rdf2json.properties.PropertyValueLiteral cannot be cast to class uk.ac.ebi.rdf2json.properties.PropertyValueURI (uk.ac.ebi.rdf2json.properties.PropertyValueLiteral and uk.ac.ebi.rdf2json.properties.PropertyValueURI are in unnamed module of loader 'app')
	at uk.ac.ebi.rdf2json.annotators.RelatedAnnotator.lambda$annotateRelated_Class_subClassOf_Restriction_someValuesFrom_oneOf$2(RelatedAnnotator.java:218)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at uk.ac.ebi.rdf2json.annotators.RelatedAnnotator.annotateRelated_Class_subClassOf_Restriction_someValuesFrom_oneOf(RelatedAnnotator.java:219)
	at uk.ac.ebi.rdf2json.annotators.RelatedAnnotator.annotateRelated_Class_subClassOf_Restriction_someValuesFrom(RelatedAnnotator.java:194)
	at uk.ac.ebi.rdf2json.annotators.RelatedAnnotator.annotateRelated_Class_subClassOf_Restriction(RelatedAnnotator.java:149)
	at uk.ac.ebi.rdf2json.annotators.RelatedAnnotator.annotateRelated(RelatedAnnotator.java:52)
	at uk.ac.ebi.rdf2json.OntologyGraph.<init>(OntologyGraph.java:307)
	at uk.ac.ebi.rdf2json.RDF2JSON.main(RDF2JSON.java:152) 
</details>

**Comment by giraygi** [comment]
fibo can only be ingested by disabling the 307th line  in OntologyGraph.java which is `RelatedAnnotator.annotateRelated(this);`
