### ISSUE TITLE
Neo4j 5

### ISSUE THREAD

**Issue by giraygi** [TIBHannover/ols4#8]
**Is your feature request related to a problem? Please describe.**
Neo4J version 5 enables multiple imports to the database

**Describe the solution you'd like**
Upgrading to latest Neo4J 5.1 would be ideal. However, this will also require upgrading to JDK version 17

**Describe alternatives you've considered**
Multiple imports may also be tested without upgrading.

**Additional context**
There is an equivalent [issue](https://github.com/EBISPOT/ols4/issues/346) in EBISPOT ols4 repository

**Comment by giraygi** [comment]
https://github.com/neo4j/neo4j/issues/13217

**Comment by giraygi** [comment]
<details><summary>Click to expand for Neo$J version error</summary>
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
ols4-neo4j_1     |      at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:278) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:213) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:38) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:184) [neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:30) [neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@171dc7c3' was successfully initialized, but failed to start. Please see the attached cause exception "The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported".
ols4-neo4j_1     |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:364) ~[neo4j-common-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:91) ~[neo4j-common-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:269) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      ... 5 more
ols4-neo4j_1     | Caused by: org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.
ols4-neo4j_1     |      at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.assertDatabaseAvailable(DatabaseAvailabilityGuard.java:154) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginKernelTransaction(GraphDatabaseFacade.java:148) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:117) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:89) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:113) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:107) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:102) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTx(GraphDatabaseTransactions.java:93) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.dbms.database.SystemGraphComponents.initializeSystemGraph(SystemGraphComponents.java:83) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.dbms.database.DefaultSystemGraphInitializer.initializeSystemGraph(DefaultSystemGraphInitializer.java:38) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.dbms.database.SystemGraphInitializer.start(SystemGraphInitializer.java:27) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:347) ~[neo4j-common-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:91) ~[neo4j-common-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:269) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      ... 5 more
ols4-neo4j_1     | Caused by: org.neo4j.kernel.impl.storemigration.UnableToMigrateException: The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported
ols4-neo4j_1     |      at org.neo4j.kernel.impl.storemigration.StoreMigrator.doUpgradeCheck(StoreMigrator.java:393) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.impl.storemigration.StoreMigrator.upgradeIfNeeded(StoreMigrator.java:248) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.database.Database.upgradeStore(Database.java:784) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.database.Database.specificStart(Database.java:415) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.database.AbstractDatabase.start(AbstractDatabase.java:160) ~[neo4j-kernel-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.dbms.database.DatabaseLifecycles.startDatabase(DatabaseLifecycles.java:123) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.dbms.database.DatabaseLifecycles$SystemDatabaseStarter.start(DatabaseLifecycles.java:146) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:347) ~[neo4j-common-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:91) ~[neo4j-common-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:269) ~[neo4j-5.19.0.jar:5.19.0]
ols4-neo4j_1     |      ... 5 more
</details>

**Comment by giraygi** [comment]
https://www.baeldung.com/java-split-string-commas
